---
- name: file for deploying hostnames
  hosts: all
  tasks: 
   
   - name: using jinja template to deploy 
     template:
      src: hosts.j2
      dest: /etc/myhosts
     when: inventory_hostname in groups['dev'] 
