---
- name: report
  hosts: all 
  tasks: 
   
   - name: download the file 
     get_url: 
      url: http://servera/hwreport.empty
      dest: /root/hwreport.txt

   - name: lineinfile 
     lineinfile:
      path: /root/hwreport.txt
      regexp: "{{ item.name }}"
      line: "{{ item.name }} = {{ item.value }}"
     loop:

      - name: HOST
        value: "{{ inventory_hostname}}"
      - name: MEMORY
        value: "{{ ansible_memtotal_mb }}"
      - name: BIOS
        value: "{{ ansible_bios_version}}"
      - name: VDA_DISK_SIZE
        value: "{{ ansible_devices.vda.size | default ('None') }}"
      - name: VDB_DISK_SIZE
        value: "{{ ansible_devices.vdb.size | default ('None') }}"  
      - name: VDD_DISK_SIZE
        value: "{{ ansible_devices.vdd.size | default ('None') }}"
