---
dependencies: []
# CentOS-7 may require ome.selinux_utils

galaxy_info:
  role_name: haproxy
  author: "ome-devel@lists.openmicroscopy.org.uk (upstream: geerlingguy)"
  description: HAProxy installation and configuration.
  company: Open Microscopy Environment
  license: "license (BSD, MIT)"
  min_ansible_version: 2.3
  platforms:
    - name: EL
      versions:
        - 7
    - name: Ubuntu
      versions:
        - xenial
  galaxy_tags:
    - web
    - networking
    - cloud
